before_install:
- pip install --upgrade pip wheel
language: python
cache: apt
sudo: false
python:
- '3.4'
install:
- pip install Nikola
- pip install "Nikola[extras]"
script:
- nikola build
after_success:
- bash deploy.sh
env:
  global:
  - secure: oAcL5TQwwyigLGgs+kwWqMlo3MOLLVlI4flu+KHwU+kqh+yhwLdfN+otb2stSelF6pAMJ/UV3lrLryJf6CHcn5OrL8k4a/D3phZs2HY/vSZ0C2f+SZWLXU0QFxmtlhDANTN+QyPHhUFgqTBf+vgcJpb84VLFfasMvzJuOKzKI0usoEmFQxtfVmTKGnBpm7lMP+uzcqWr6KZziEGkBVJL8snliYyAoHyJIXVdk5YKWn4dbHKmNxlE2mIInjcellWw/YdaHBlmwT8PghPKPYLaclzzxHr5W/GIeNt9gtiUxO+5J7lmcct/4BgYlnuMtS9UGZnEmrHJNw22deoHIqNpsaZjEsfUROw+AnL2aMLCuP7P8dkpREgtqNWG+mbugONOIQa45zP97sHD8xwAcIiHpFYwlB2/dlCdR5m0YxnkUdbiE4h36iaos3t0ClwAB4jM3o1vZ/xBAO2TPFxcOXFAEABq1T3z70+NWLTWRaQXI+WSeO1bUKcX6S/Y8JFX8HOJR1hVrvj8f1xlKKDA3o+8/y421X+J4p+XGO2zABYD/cyNJnOgjhTI0n7E3E5mVrl/nAmIqgOnRD590sKEwpj7SNGHxI77bIIUSj4z5yJygkOMh+cqgTI1lFD/BmhLbHHWDW2LX04vBp9JXbC7JtiHhXuS3fMfIYMzMjVI6Sp9+kI=
